import * as React from "react"
import * as styles from "./terms.module.scss"

const TermsOfService = () => (
    <div className={styles.terms}>
        <div className={styles.termsWrap}>
            <div className={styles.termsTxt}>
                <strong>Kiwi Browser - Terms of Service</strong> <br />
                Below is the formal text for our terms of service, to learn about our business model and our privacy policy in a simplified way, you can go here<br />
                <br />
                Read the end user license agreement for Kiwi Browser and find out how to get in touch if you have any questions about regarding our EULA.<br />
                <br />
                Last updated: Aug 3, 2020<br />
                Last updated: May 27, 2022 (added more contact information)<br />
                <br />
                1. This End User License Agreement (“EULA”) governs your use (“You”) of the browser software in executable form (“Software”) and any ancillary services (“Services”) provided to You by Geometry OU (“Kiwi Browser”) to the exclusion of all other terms and conditions.<br />
                <br />
                2. Here at Kiwi Browser, we try to keep things as simple and easy as possible but since this is a legal document, it’s a bit longer than we would like it to be. It’s important that you read this carefully and understand the terms of use. By using the software, you agree to the following terms and conditions. If you don’t agree to the following terms and conditions, you are not allowed to use Kiwi Browser Software or Services.<br />
                <br />
                If you have any questions or concerns regarding the terms herein, please email Geometry OU at team at geometry.ee. Do not use the Find dot Kiwi or Kiwi Browser Products until your questions and concerns have been answered to your satisfaction and you agree to abide by the EULA. Notice to consumers: Depending on the laws of the jurisdiction where you live, you may have certain rights that cannot be waived through this agreement, are in addition to the terms of this agreement, and/or certain provisions of this agreement may be unenforceable as to you. To the extent that any term of this agreement is unenforceable, the remainder of the agreement shall remain in full force and effect. If you have questions regarding your rights under your local consumer protection laws, please consult with your government's consumer protection agency or a local consumer advocacy group. By downloading a Find dot Kiwi Product, you will be installing a software application or browser onto your computer (depending on the product). The Kiwi Browser and Find dot Kiwi will allow you to search the Internet, and may provide you with additional features as further described in this EULA. Certain search features, as well as other non-search-related features may be customized by you.<br />
                <br />
                3. We may modify this EULA and the Privacy Policy at any time. When we post changes to this EULA, we will include the date when this EULA was last updated. If there are significant changes to the Kiwi Browser EULA, we will notify you either by prominently posting a notice of such changes or by directly sending you a notification.<br />
                <br />
                4. Description of Other Rights and Limitations<br />
                <br />
                A) Restricted Use. You may not rent, sell, lease, sublicense, distribute, assign, copy (other than a single copy for your own backup purposes), or in any way transfer the Find dot Kiwi Products or use the Find dot Kiwi Products for the benefit of any third party. You may not install the Kiwi Browser Find dot Kiwi Products on any computer without permission from the owner of that computer or mobile phone.<br />
                You agree that you will not use any robot, spider, other automatic or manual device or process to interfere or attempt to interfere with the proper working of the Find dot Kiwi Products, except to remove our Find dot Kiwi Products from a computer of which you are an owner or authorized user. You may not violate or attempt to violate the security of our services. You may not modify, reverse-engineer, decompile, disassemble, or otherwise tamper with any Find dot Kiwi Products, or attempt to do so for any reason. You may not access, create or modify the source code of any Find dot Kiwi Products in any way. You do not have the right to and may not create derivative works of any Find dot Kiwi Products. All modifications or enhancements to an Find dot Kiwi Products remain the sole property of Geometry OU.<br />
                <br />
                B) Find dot Kiwi Products Updates. We reserve the right to add or remove features or functions to existing Find dot Kiwi Products. We may require the updating of the Find dot Kiwi Products on your computer when we release a new version of the Find dot Kiwi Products, or when we make new features available. This update may occur automatically or upon prior notice to you, and may occur all at once or over multiple sessions. You understand that we may require your review and acceptance of our then-current EULA before you will be permitted to use any subsequent versions of the Find dot Kiwi Products. You acknowledge and agree that we have no obligation to make available to you any subsequent versions of the Find dot Kiwi Products.<br />
                <br />
                C) Mobile Usage. If you access an Find dot Kiwi Product through a mobile network, your network or roaming provider's messaging, data and other rates and fees may apply. Downloading, installing or using certain Find dot Kiwi Products may be prohibited or restricted by your network provider and not all Find dot Kiwi Products may work with your network provider or device.<br />
                <br />
                5. Subject to the terms and conditions herein, Kiwi Browser hereby grants You a limited, non-exclusive, non-transferable, non-sublicensable license to install and use the Software and Services for its intended purpose.<br />
                <br />
                6. You may use the Software and Services on your personal computer, including your laptop, desktop and handheld device. You may only use the Software and Services for personal use. By way of example, this means that although You are allowed to use our Software and Services at work or within your business or organization, You are not allowed to sell, trade or resell the Software or Services for any purpose, including without limitation any use in any application service provider environment, service bureau, or time-sharing arrangements<br />
                <br />
                7. Without limiting the foregoing, you are neither allowed to (a) adapt, alter, translate, embed into any other product or otherwise create derivative works of, or otherwise modify the Software ; (b) separate the component programs of the Software for use on different computers; (c) reverse engineer, decompile, disassemble or otherwise attempt to derive the source code for the Software, except as permitted by applicable law; or (d) remove, alter or obscure any proprietary notices on the Software or the applicable documentation therein.<br />
                <br />
                8. The Software and Services and all intellectual property rights therein are the exclusive property of Kiwi Browser and its suppliers, and all rights in and to the Software not expressly granted to You in this EULA are reserved. Kiwi Browser owns all copies of the Software, however made.<br />
                <br />
                9. By accepting this EULA, You also accept our privacy policy (available at https://privacy.kiwibrowser.org/). Here at Kiwi Browser we take privacy matters very seriously and we always strive to be compliant with applicable laws and regulations.<br />
                <br />
                10. The Software and Services are provided to you “as is” without any warranty of any kind, which hereby is disclaimed. Without limiting the foregoing we do not guarantee availability of our Software and Services. You use our Software and Services at your own risk, and You agree to be fully responsible for any claim, expense, liability and/or losses arising from any infringement of this EULA. Even though we do our best to provide You with great Software and Services, we cannot be held liable for any kind of damage, direct or indirect or consequential, resulting from your use of our Software and Services.<br />
                <br />
                11. The Find dot Kiwi Products and Kiwi Browser, including all code, content, protocols, software, and documentation provided to you by Geometry OU are Geometry OU's property or the property of Geometry OU's licensors, and are protected by U.S. and international copyright, trademarks, patents and other proprietary rights and laws relating to Intellectual Property Rights. "Intellectual Property Rights" means, collectively, rights under patent, trademark, copyright and trade secret laws, and any other intellectual property or proprietary rights recognized in any country or jurisdiction worldwide, including, without limitation, moral or similar rights. You may not delete, alter, or remove any copyright, trademark, or other proprietary rights notice we have placed on the Find dot Kiwi Products. All rights not expressly granted hereunder are expressly reserved to Licensor and its licensors. The Geometry OU name, logos and affiliated properties, Kiwi Browser, are the exclusive property of Geometry OU. All other trademarks appearing on any Find dot Kiwi Product are trademarks of their respective owners. Our partners or service providers may also have additional proprietary rights in the content which they make available through an Find dot Kiwi Product. The trade names, trademarks and service marks owned by us, whether registered or unregistered, may not be used in connection with any product or service that is not ours, in any manner that is likely to cause confusion. Nothing contained in herein should be construed as granting, by implication, estoppel or otherwise, any license or right to use any of our trade names, trademarks or service marks without our express prior written consent.<br />
                <br />
                12. This EULA applies from the time you download or activate the Software, and continues in perpetuity unless terminated by Kiwi Browser for no cause with thirty (30) days prior written notice, or terminated because of Your breach of this EULA. On termination all rights granted in this EULA lapse and You are not allowed to use the Software or Services. All provisions herein that by its nature are intended to survive termination, including Section 10 and 12, shall survive such termination.<br />
                <br />
                13. Kiwi Browser’s headquarters are based in the city of Tallinn, Estonia. This EULA is therefore governed by the laws of Estonia, except its conflict of laws rules and regulations. All disputes, actions or proceedings arising under or related to this EULA shall exclusively be referred and resolved by the Harjumaa Court. Notwithstanding, nothing in this EULA will be deemed as preventing Kiwi Browser from seeking injunctive relief (or any other provisional remedy) from any court having jurisdiction over the parties and the subject matter of the dispute as is necessary to protect Kiwi Browser’s proprietary information, trade secrets, know-how, or any other intellectual property rights.<br />
                <br />
                14. Disclaimer of Warranty<br />
                ALL FIND DOT KIWI PRODUCTS ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, AND YOU USE THEM AT YOUR SOLE RISK. GEOMETRY OU EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY OTHER WARRANTY ARISING UNDER THE UNIFORM COMMERCIAL CODE, USAGE OF TRADE, COURSE OF CONDUCT OR OTHERWISE. WITHOUT LIMITATION, Geometry OU MAKES NO WARRANTY THAT THE FIND DOT KIWI OR KIWI BROWSER PRODUCT WILL MEET YOUR REQUIREMENTS, THAT THEY WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, THAT THE RESULTS OBTAINED FROM THE USE OF THE Find dot Kiwi PRODUCTS WILL BE ACCURATE OR RELIABLE, OR THAT THE QUALITY OF THE KIWI BROWSER PRODUCT OBTAINED WILL MEET YOUR EXPECTATIONS.<br />
                THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF AN FIND DOT KIWI PRODUCT REMAINS SOLELY WITH YOU.<br />
                GEOMETRY OU EXPRESSLY DISCLAIMS ALL WARRANTIES RELATING TO PRODUCTS AND/OR SERVICES PROVIDED BY THIRD PARTY PARTNERS.<br />
                SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES. IN SUCH JURISDICTIONS, THE FOREGOING DISCLAIMERS MAY NOT APPLY TO YOU INSOFAR AS THEY RELATE TO IMPLIED WARRANTIES.<br />
                THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS AGREEMENT.<br />
                <br />
                15. Limitation of Liability<br />
                YOU EXPRESSLY UNDERSTAND AND AGREE THAT GEOMETRY OU SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF GEOMETRY OU HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (I) THE USE OR THE INABILITY TO USE THE FIND DOT KIWI PRODUCT; (II) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (III) STATEMENTS OR CONDUCT OF ANY THIRD PARTY; OR (IV) ANY OTHER MATTER RELATING TO THE Find dot Kiwi PRODUCT. IN NO EVENT SHALL GEOMETRY OU'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE), OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING AN Find dot Kiwi PRODUCT.<br />
                IF ANY OF THE EXCLUSIONS SET FORTH IN THIS SECTION IS DETERMINED BY A COURT OF COMPETENT JURISDICTION TO BE UNENFORCEABLE, THEN ALL SUCH EXPRESS, IMPLIED AND STATUTORY WARRANTIES SHALL BE LIMITED IN DURATION FOR A PERIOD OF THIRTY (30) DAYS AFTER THE DATE ON WHICH YOU FIRST ACCESS THE FIND DOT KIWI OR KIWI BROWSER PRODUCT, AND NO WARRANTIES SHALL APPLY AFTER SUCH PERIOD.<br />
                <br />
                16. Indemnification<br />
                YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS GEOMETRY OU, ITS PARENTS, AFFILIATE AND SUBSIDIARY COMPANIES, OFFICERS, DIRECTORS, EMPLOYEES, CONSULTANTS AND AGENTS FROM ANY AND ALL THIRD PARTY CLAIMS, LIABILITY, DAMAGES AND/OR COSTS (INCLUDING, BUT NOT LIMITED TO, ATTORNEYS' FEES) ARISING FROM YOUR USE OF THE FIND DOT KIWI PRODUCTS, YOUR VIOLATION OF THE EULA OR YOUR INFRINGEMENT, OR INFRINGEMENT BY ANY OTHER USER OF YOUR ACCOUNT, OF ANY INTELLECTUAL PROPERTY OR OTHER RIGHT OF ANY PERSON OR ENTITY. YOU AGREE TO IMMEDIATELY NOTIFY GEOMETRY OU OF ANY UNAUTHORIZED USE OF YOUR ACCOUNT OR ANY OTHER BREACH OF SECURITY KNOWN TO YOU.<br />
                <br />
                17. Notice to Government End Users<br />
                Any Geometry OU Products installed for or on behalf of the United States of America, its agencies and/or instrumentalities ("U.S. Government"), is provided with Restricted Rights as "commercial Items," as that terms is defined at 48 C.F.R. §2.101, consisting of "Commercial Computer Software" and "Commercial Computer Software Documentation," as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable. Pursuant to Federal Acquisition Regulation 12.212 (48 C.F.R. §12.212), the U.S. Government shall have only those rights specified in the license contained herein. The U.S. Government shall not be entitled to (i) technical information that is not customarily provided to the public or to (ii) use, modify, reproduce, release, perform, display, or disclose commercial computer software or commercial computer software documentation except as specified herein. Use, duplication, or disclosure by the U.S. Government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the Commercial Computer Software - Restricted Rights at 48 C.F.R. 52.227-19, as applicable.
                <br />
                18. How to Contact Us<br />
                If you have any questions about this EULA or our information-handling practices, or wish to review, amend or delete any personal information we are storing, please contact us by email or postal mail as follows:<br />
                DPO: Arnaud GRANAL<br />
                Geometry OU<br />
                Sepapaja tn 6<br />
                15551 Tallinn<br />
                Estonia<br />
                +372 618 8240<br />
                team at geometry.ee
            </div>
        </div>
    </div>
)

export default TermsOfService
